// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtoRehber.Models;

#nullable disable

namespace OtoRehber.Migrations
{
    [DbContext(typeof(OtoRehberDbContext))]
    [Migration("20260720190924_AddChronicIssues")]
    partial class AddChronicIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("OtoRehber.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedMaintenanceCostEUR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpertSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ReliabilityScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Volkswagen",
                            Cons = "[\"DSG \\u015Fanz\\u0131man riski\",\"Dizel motor partik\\u00FCl filtresi\",\"Y\\u00FCksek servis maliyeti\"]",
                            Engine = "1.6 TDI",
                            EstimatedMaintenanceCostEUR = 400,
                            ExpertSummary = "C segmentinin referans modeli, kaliteli iç mekan ve tok sürüş hissi sunar. Ancak DSG şanzıman ve dizel motor bakım maliyetlerine dikkat edilmelidir.",
                            ModelName = "Golf",
                            PriceRange = "800k - 1.2M TL",
                            Pros = "[\"Kaliteli i\\u00E7 mekan\",\"Tok s\\u00FCr\\u00FC\\u015F hissi\",\"\\u0130yi 2. el de\\u011Feri\"]",
                            ReliabilityScore = 8.0,
                            Segment = "C"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Toyota",
                            Cons = "[\"Zay\\u0131f yal\\u0131t\\u0131m\",\"Vasat performans\",\"Demode i\\u00E7 tasar\\u0131m\"]",
                            Engine = "1.6 Valvematic",
                            EstimatedMaintenanceCostEUR = 200,
                            ExpertSummary = "Sorunsuzluk dendiğinde akla ilk gelen model. Konfor odaklı, aile kullanımına çok uygun fakat performans beklentisi olanları üzebilir.",
                            ModelName = "Corolla",
                            PriceRange = "700k - 1.1M TL",
                            Pros = "[\"M\\u00FCkemmel sorunsuzluk\",\"Geni\\u015F i\\u00E7 hacim\",\"D\\u00FC\\u015F\\u00FCk i\\u015Fletme maliyeti\"]",
                            ReliabilityScore = 9.5,
                            Segment = "C"
                        });
                });

            modelBuilder.Entity("OtoRehber.Models.ChronicIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AffectedYears")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedCostEUR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("ChronicIssues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffectedYears = "2013-2018",
                            CarId = 1,
                            Description = "Özellikle kuru kavramalı 7 ileri DSG şanzımanlarda dur-kalk trafikte ısınma ve mekatronik arızası.",
                            EstimatedCostEUR = 1200,
                            IssueTitle = "DSG Şanzıman Mekatronik Arızası",
                            Severity = "Kritik"
                        },
                        new
                        {
                            Id = 2,
                            AffectedYears = "2013-2020",
                            CarId = 1,
                            Description = "Düşük devirlerde şehir içi kullanımda kurum bağlaması ve tıkanıklık.",
                            EstimatedCostEUR = 500,
                            IssueTitle = "EGR ve Partikül Filtresi",
                            Severity = "Orta"
                        });
                });

            modelBuilder.Entity("OtoRehber.Models.ChronicIssue", b =>
                {
                    b.HasOne("OtoRehber.Models.Car", "Car")
                        .WithMany("ChronicIssues")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("OtoRehber.Models.Car", b =>
                {
                    b.Navigation("ChronicIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
