// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtoRehber.Infrastructure.Data;

#nullable disable

namespace OtoRehber.Migrations
{
    [DbContext(typeof(OtoRehberDbContext))]
    [Migration("20260629082945_VeriEklemeyiGuncelle")]
    partial class VeriEklemeyiGuncelle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("OtoRehber.Infrastructure.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedMaintenanceCostEUR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpertSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ReliabilityScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Volkswagen",
                            Cons = "[]",
                            Engine = "1.6 TDI",
                            EstimatedMaintenanceCostEUR = 0,
                            ExpertSummary = "C segmentinin referans modeli.",
                            ModelName = "Golf",
                            PriceRange = "800k - 1.2M TL",
                            Pros = "[]",
                            ReliabilityScore = 8.0,
                            Segment = "C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
