// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtoRehber.Infrastructure.Data;

#nullable disable

namespace OtoRehber.Migrations
{
    [DbContext(typeof(OtoRehberDbContext))]
    [Migration("20260720192329_AddProsConsTable")]
    partial class AddProsConsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("OtoRehber.Infrastructure.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedMaintenanceCostEUR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpertSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ReliabilityScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Volkswagen",
                            Engine = "1.6 TDI",
                            EstimatedMaintenanceCostEUR = 400,
                            ExpertSummary = "C segmentinin referans modeli, kaliteli iç mekan ve tok sürüþ hissi sunar. Ancak DSG þanzýman ve dizel motor bakým maliyetlerine dikkat edilmelidir.",
                            ModelName = "Golf",
                            PriceRange = "800k - 1.2M TL",
                            ReliabilityScore = 8.0,
                            Segment = "C"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Toyota",
                            Engine = "1.6 Valvematic",
                            EstimatedMaintenanceCostEUR = 200,
                            ExpertSummary = "Sorunsuzluk dendiðinde akla ilk gelen model. Konfor odaklý, aile kullanýmýna çok uygun fakat performans beklentisi olanlarý üzebilir.",
                            ModelName = "Corolla",
                            PriceRange = "700k - 1.1M TL",
                            ReliabilityScore = 9.5,
                            Segment = "C"
                        });
                });

            modelBuilder.Entity("OtoRehber.Infrastructure.Data.ChronicIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AffectedYears")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedCostEUR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("ChronicIssues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffectedYears = "2013-2018",
                            CarId = 1,
                            Description = "Özellikle kuru kavramalý 7 ileri DSG þanzýmanlarda dur-kalk trafikte ýsýnma ve mekatronik arýzasý.",
                            EstimatedCostEUR = 1200,
                            IssueTitle = "DSG Þanzýman Mekatronik Arýzasý",
                            Severity = "Kritik"
                        },
                        new
                        {
                            Id = 2,
                            AffectedYears = "2013-2020",
                            CarId = 1,
                            Description = "Düþük devirlerde þehir içi kullanýmda kurum baðlamasý ve týkanýklýk.",
                            EstimatedCostEUR = 500,
                            IssueTitle = "EGR ve Partikül Filtresi",
                            Severity = "Orta"
                        });
                });

            modelBuilder.Entity("OtoRehber.Infrastructure.Data.ProsCons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("ProsCons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Description = "Kaliteli iç mekan",
                            Type = "Pro"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 1,
                            Description = "Tok sürüþ hissi",
                            Type = "Pro"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 1,
                            Description = "Ýyi 2. el deðeri",
                            Type = "Pro"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 1,
                            Description = "DSG þanzýman riski",
                            Type = "Con"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 1,
                            Description = "Dizel motor partikül filtresi",
                            Type = "Con"
                        },
                        new
                        {
                            Id = 6,
                            CarId = 1,
                            Description = "Yüksek servis maliyeti",
                            Type = "Con"
                        },
                        new
                        {
                            Id = 7,
                            CarId = 2,
                            Description = "Mükemmel sorunsuzluk",
                            Type = "Pro"
                        },
                        new
                        {
                            Id = 8,
                            CarId = 2,
                            Description = "Geniþ iç hacim",
                            Type = "Pro"
                        },
                        new
                        {
                            Id = 9,
                            CarId = 2,
                            Description = "Düþük iþletme maliyeti",
                            Type = "Pro"
                        },
                        new
                        {
                            Id = 10,
                            CarId = 2,
                            Description = "Zayýf yalýtým",
                            Type = "Con"
                        },
                        new
                        {
                            Id = 11,
                            CarId = 2,
                            Description = "Vasat performans",
                            Type = "Con"
                        },
                        new
                        {
                            Id = 12,
                            CarId = 2,
                            Description = "Demode iç tasarým",
                            Type = "Con"
                        });
                });

            modelBuilder.Entity("OtoRehber.Infrastructure.Data.ChronicIssue", b =>
                {
                    b.HasOne("OtoRehber.Infrastructure.Data.Car", "Car")
                        .WithMany("ChronicIssues")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("OtoRehber.Infrastructure.Data.ProsCons", b =>
                {
                    b.HasOne("OtoRehber.Infrastructure.Data.Car", "Car")
                        .WithMany("ProsConsList")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("OtoRehber.Infrastructure.Data.Car", b =>
                {
                    b.Navigation("ChronicIssues");

                    b.Navigation("ProsConsList");
                });
#pragma warning restore 612, 618
        }
    }
}
